config/routes.rb
Rails.application.routes.draw do

  root to: 'users#new'

  get 'users/new' => 'users#new', as: :new_user

  post 'users' => 'users#create'

  get '/login'     => 'sessions#new'

  post '/login'    => 'sessions#create'

  delete '/logout' => 'sessions#destroy'

  get '/realestate' => 'realestate#new', as: :new_realestate

  post '/realestate' =>'realestate#create'

  get '/house' => 'house#new'

  post '/house' => 'house#create'

  get '/house/show' => 'house#show'

  get '/house/:id/interested' => 'house#interest', as: :house_interested

  get '/realestate/show' => 'realestate#show'

  get '/user/:id/edit' => 'users#edit', as: :user_edit

  post '/user/:id/edit' => 'users#update'

  get '/house/:id/edit' => 'house#edit', as: :house_edit

  post '/house/:id/edit' => 'house#update'

  get '/user/menu' => 'users#menu'

  get '/user/show' => 'users#show'

  get '/realestate/:id/edit' => 'realestate#edit', as: :realestate_edit

  post '/realestate/:id/edit' => 'realestate#update'

  get 'inquiry/new' => 'inquiry#new', as: :new_inquiry

  post 'inquiry/new' => 'inquiry#create'

  get 'inquiry/show' => 'inquiry#show'

  get 'inquiry/:id/edit' => 'inquiry#edit'

  post 'inquiry/:id/edit' => 'inquiry#update', as: :inquiry_edit

  get 'inquiry/:id/reply' => 'inquiry#reply', as: :inquiry_reply

  post 'inquiry/:id/reply' => 'inquiry#reply_update'

  get '/users/:id/destroy' => 'users#destroy', as: :users_destroy

  get '/inquiry/:id/destroy' => 'inquiry#destroy', as: :inquiry_destroy

  get '/house/:id/destroy' => 'house#destroy', as: :house_destroy

  get '/realestate/:id/destroy' => 'realestate#destroy', as: :realestate_destroy
end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password
  if User.count == 0
    User.create({:name => "Admin", :email => "admin@admin.com", :password => "admin", :password_confirmation =>"admin", :user_type => "Admin"})
  end
  # Verify that email field is not blank and that it doesn't already exist in the db (prevents duplicates):
  validates :name, :presence => {:message => "Name cannot be empty"}
  validates :email, presence: true, uniqueness: true

  belongs_to :realestate
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_action :logged_in_user, only: [:edit, :show, :menu]

  def new
    @user = User.new
  end

  def menu
    @user = User.find(current_user.id)
  end

  def create
    @user = User.new(user_params)
    #print user_params
    # store all emails in lowercase to avoid duplicates and case-sensitive login errors:
    #@user.email.downcase!

    if @user.save
      # If user saves in the db successfully:
      flash[:notice] = "Account created successfully!"

      if current_user != nil
        if current_user.user_type == 'Admin'
          redirect_to user_menu_path
        end
      else
        redirect_to login_path
      end


    else
      # If user fails model validation - probably a bad password or duplicate email:
      flash.now.alert = "Oops, couldn't create account"
      flash.now.alert = @user.errors.full_messages
      render :new
    end
  end

  def show
    @user = User.all
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update_attributes(user_params)
      # Handle a successful update.
      flash[:notice] = "Updated successfully!"
      redirect_to user_menu_path
    else
      render 'edit'
    end
  end

  def destroy
    @user = User.find_by_id(params[:id])
    if @user != nil
      User.find(params[:id]).destroy
      flash[:notice] = "User deleted"
      redirect_to user_show_path
    else
      flash[:notice] = "Record not found"
    end

  end



  private

  def user_params
    # strong parameters - whitelist of allowed fields #=> permit(:name, :email, ...)
    # that can be submitted by a form to the user model #=> require(:user)
    params.require(:user).permit(:name, :email, :password, :password_confirmation, :user_type, :phone, :preferred_contact, :company_name, :house_interested)
  end

  # Before filters
  def logged_in?
    !current_user.nil?
  end

  # Confirms a logged-in user.
  def logged_in_user
    unless logged_in?
      flash[:notice] = "Please log in."
      redirect_to login_path
    end
  end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/edit.html.erb
<% provide(:title, "Edit user") %>
<h1>Update your profile</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for :user do |f| %>

      <%= f.label :name %>
      <%= f.text_field :name, class: 'form-control' %>
      </br>
      <%= f.label :email %>
      <%= f.email_field :email, class: 'form-control' %>
      </br>
      <%= f.label :password %>
      <%= f.password_field :password, class: 'form-control' %>
      </br>
      <%= f.label :password_confirmation, "Confirmation" %>
      <%= f.password_field :password_confirmation, class: 'form-control' %>
      </br>
      <%= f.label :phone %>
      <%= f.text_field :phone, class: 'form_control' %>
      </br>
      <%= f.label :preferred_contact %>
      <%= f.select :preferred_contact, %w[Text Email] %>
      </br>
      <% if current_user.user_type === 'Realtor' %>
        <%= f.label "Choose Company" %>
        <%= f.collection_select :company_name, Realestate.order(:name), :id, :name, include_blank: true %>
        <%= link_to "Create New Company", realestate_path %>
        </br>
      <% end %>
      <%= f.submit "Save changes", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/users/menu.html.erb
<body data-turbolinks = "false">
<h2> Welcome, <%= current_user.name%></h2>
<br>
<br>

<% if current_user.user_type === 'Admin' %>
  <h4><%= link_to "Real Estate Companies", realestate_show_path%></h4>
  <h4><%= link_to "Create Realtor/House Hunter", new_user_path %></h4>
<% end %>
<h4><%= link_to "Houses", house_show_path%></h4>
<%if current_user.user_type == 'Realtor' %>
  <h4><%= link_to "Create company", new_realestate_path %></h4>
  <h4><%= link_to "Edit company",realestate_edit_path(current_user) %></h4>
  <%end %>
<% if current_user.user_type === 'Admin' %>
  <h4><%= link_to "Users", user_show_path%></h4>
<% end %>
<% if current_user.user_type === 'Realestate Hunter' %>
  <h4><%= link_to "Real Estate Companies",realestate_show_path %></h4>
  <h4><%= link_to "Post Inquiries", new_inquiry_path %></h4>
  <h4><%= link_to "View my inquiries", inquiry_show_path %></h4>
<% end %>
<% if current_user.user_type === 'Admin' || current_user.user_type === 'Realtor' %>
  <h4><%= link_to "View Inquiries", inquiry_show_path %></h4>
<% end %>
<% if current_user.user_type === 'Realtor' %>
  <h4><%= link_to "Edit Company Details", realestate_edit_path(current_user.company_name.to_i) %></h4>
<% end %>
</body>

app/views/users/new.html.erb
<% if current_user == nil %>
<h1>Sign Up</h1>
<%else %>
  <h1>Create new House Hunter/Realtor</h1>
<%end %>

<%= form_for @user do |f| %>
  <div>
    <%= f.label :name %>
    <%= f.text_field :name, autofocus: true %>
  </div>
  <div>
    <%= f.label :email %>
    <%= f.text_field :email %>
  </div>

  <div>
    <%= f.label :password %>
    <%= f.password_field :password %>
  </div>
  <div>
    <%= f.label :password_confirmation %>
    <%= f.password_field :password_confirmation %>
  </div>
  <div class="field">
    <b>Users</b><br />
    <%= f.radio_button :user_type, 'Realtor' %> Realtor<br />
    <%= f.radio_button :user_type, 'Realestate Hunter' %> House Hunter<br />

  </div>
  <div>
    <%= f.label :phone %>
    <%= f.text_field :phone %>
  </div>
  <div>
    <%= f.label :preferred_contact %>
    <%= f.select :preferred_contact, %w[Text Email] %>
  </div>

  <div>
    <%= f.submit "Sign up!" %>
  </div>

<% end %>

app/views/users/show.html.erb
<h2>User Details</h2>
<% @users = User.all %>
<table id="users" role="datatable">
  <thead>
  <tr>
    <th>Name</th>
    <th>Email</th>
    <th>User Type</th>
    <th>Phone</th>
    <th>Preferred Contact</th>
    <th>Edit</th>
    <th>Destroy</th>
  </tr>
  </thead>
  <tbody>
  <% @users.each do |user| %>
  <% if user.user_type!= "Admin" %>
    <tr>
      <td>
        <%= user.name %>
      </td>

      <td>
        <%= user.email %>
      </td>

      <td>
        <%= user.user_type %>
      </td>

      <td>
        <%= user.phone %>
      </td>

      <td>
        <%= user.preferred_contact %>
      </td>
      <td>
        <%= link_to "Edit", user_edit_path(user.id) %>
      </td>
      <td>
        <%= link_to "Delete", users_destroy_path(user.id) %>
      </td>
    </tr>
  <%end %>
  <% end %>
  </tbody>
</table>


<%= link_to 'Back', user_menu_path, :class => 'button' %>