config/routes.rb
Rails.application.routes.draw do

  root to: 'users#new'

  get 'users/new' => 'users#new', as: :new_user

  post 'users' => 'users#create'

  get '/login'     => 'sessions#new'

  post '/login'    => 'sessions#create'

  delete '/logout' => 'sessions#destroy'

  get '/realestate' => 'realestate#new', as: :new_realestate

  post '/realestate' =>'realestate#create'

  get '/house' => 'house#new'

  post '/house' => 'house#create'

  get '/house/show' => 'house#show'

  get '/house/:id/interested' => 'house#interest', as: :house_interested

  get '/realestate/show' => 'realestate#show'

  get '/user/:id/edit' => 'users#edit', as: :user_edit

  post '/user/:id/edit' => 'users#update'

  get '/house/:id/edit' => 'house#edit', as: :house_edit

  post '/house/:id/edit' => 'house#update'

  get '/user/menu' => 'users#menu'

  get '/user/show' => 'users#show'

  get '/realestate/:id/edit' => 'realestate#edit', as: :realestate_edit

  post '/realestate/:id/edit' => 'realestate#update'

  get 'inquiry/new' => 'inquiry#new', as: :new_inquiry

  post 'inquiry/new' => 'inquiry#create'

  get 'inquiry/show' => 'inquiry#show'

  get 'inquiry/:id/edit' => 'inquiry#edit'

  post 'inquiry/:id/edit' => 'inquiry#update', as: :inquiry_edit

  get 'inquiry/:id/reply' => 'inquiry#reply', as: :inquiry_reply

  post 'inquiry/:id/reply' => 'inquiry#reply_update'

  get '/users/:id/destroy' => 'users#destroy', as: :users_destroy

  get '/inquiry/:id/destroy' => 'inquiry#destroy', as: :inquiry_destroy

  get '/house/:id/destroy' => 'house#destroy', as: :house_destroy

  get '/realestate/:id/destroy' => 'realestate#destroy', as: :realestate_destroy
end

app/models/realestate.rb
class Realestate < ActiveRecord::Base
  validates :name, :presence => {:message => "Name cannot be empty"}
  validates :website, :presence => {:message => "Enter valid URL"}
  validates :address, :presence => {:message => "Address cannot be empty"}
  validates :size, :presence => true, :numericality => { only_integer: true, :message => "Size is an integer" }
  validates :founded, :presence => true, :numericality => { only_integer: true }, :length => {is: 4, :message => "Founded should be 4 digits long"}

  has_many :users
end

app/controllers/realestate_controller.rb
class RealestateController < ApplicationController

  def new
    @realestate = Realestate.new
  end

  def create
    @realestate = Realestate.new(realestate_params)

    if @realestate.save
      # If user saves in the db successfully:
      flash[:notice] = "Real Estate Company created successfully!"
      redirect_to user_menu_path
    else
      # If user fails model validation - probably a bad password or duplicate email:
      flash.now.alert = "Oops, couldn't create company."
      flash.now.alert = @realestate.errors.full_messages
      render :new
    end
  end

  def show
    @realestate = Realestate.all
  end

  def edit
    @realestate = Realestate.find_by_id(params[:id])
    if @realestate == nil
      flash[:notice] = "Record not found!"
      render 'show'
    end
  end

  def update
    @realestate = Realestate.find(params[:id])
    if @realestate.update_attributes(realestate_params)
      # Handle a successful update.
      flash[:notice] = "Updated successfully!"
      redirect_to @realestate
    else
      render 'edit'
    end
  end

  def destroy
    @realestate = Realestate.find_by_id(params[:id])
    if @realestate != nil
      Realestate.find(params[:id]).destroy
      flash[:notice] = "Company deleted"
      redirect_to realestate_show_path
    else
      flash[:notice] = "Record not found"
    end

  end




  private
  def realestate_params
    # strong parameters - whitelist of allowed fields #=> permit(:name, :email, ...)
    # that can be submitted by a form to the user model #=> require(:user)
    params.require(:realestate).permit(:name, :website, :address, :size, :founded, :revenue, :synopsis)
  end

end

app/helpers/realestate_helper.rb
module RealestateHelper
end

app/views/realestate/edit.html.erb
<% provide(:title, "Edit Company") %>
<h1>Edit Company Information</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for :realestate do |f| %>

      <%= f.label :name %>
      <%= f.text_field :name, class: 'form-control' %>
      </br>
      <%= f.label :website %>
      <%= f.text_field :website, class: 'form-control' %>
      </br>
      <%= f.label :address %>
      <%= f.text_field :address, class: 'form-control' %>

      </br>
      <%= f.label :size %>
      <%= f.text_field :size, class: 'form-control' %>
      </br>
      <%= f.label :founded %>
      <%= f.text_field :founded, class: 'form-control' %>

      </br>
      <%= f.label :revenue %>
      <%= f.text_field :revenue, class: 'form-control' %>

      </br>
      <%= f.label :synopsis %>
      <%= f.text_field :synopsis, class: 'form-control' %>

      </br>
      <%= f.submit "Save changes", class: "btn btn-primary" %>

      <%= link_to 'Back', realestate_show_path%>
    <% end %>
  </div>
</div>

app/views/realestate/new.html.erb
<h1>Create Real Estate Company Information</h1>

<%= form_for :realestate do |f| %>

  <div>
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div>
    <%= f.label :website %>
    <%= f.text_field :website %>
  </div>
  <div>
    Address
    <%= f.text_field :address %>
  </div>
  <div>
    <%= f.label :size %>
    <%= f.text_field :size %>
  </div>

  <div>
    <%= f.label :founded %>
    <%= f.text_field :founded %>
  </div>
  <div>
    <%= f.label :revenue %>
    <%= f.text_field :revenue %>
  </div>
  <div>
    <%= f.label :synopsis %>
    <%= f.text_field :synopsis %>
  </div>
  <div>
    <%= f.submit "Submit" %>
  </div>

<% end %>

app/views/realestate/show.html.erb
<h2>Real Estate Company and its details</h2>
<% @companies = Realestate.all %>
<table id="companies" role="datatable">
  <thead>
  <tr>
    <th>Name</th>
    <th>Website</th>
    <th>Address</th>
    <th>Size</th>
    <th>Found</th>
    <th>Revenue</th>
    <th>Synopsis</th>
    <th>Edit</th>
    <th>Destroy</th>
  </tr>
  </thead>
  <tbody>
  <% @companies.each do |company| %>
  <tr>
    <td>
      <%= company.name %>
    </td>
    <td>
      <%= company.website %>
    </td>
    <td>
      <%= company.address %>
    </td>
    <td>
      <%= company.size %>
    </td>
    <td>
      <%= company.founded %>
    </td>
    <td>
      <%= company.revenue %>
    </td>
    <td>
      <%= company.synopsis %>
    </td>
    <td>
      <%= link_to "Edit", realestate_edit_path(company.id) %>
    </td>
    <td>
      <%= link_to "Delete",realestate_destroy_path(company.id) %>
    </td>
  </tr>
  <% end %>
    </tbody>
  </table>


<% if current_user.user_type == 'Admin'%>
  <%= link_to 'Create company', new_realestate_path %>
<%end %>

<%= link_to 'Back', user_menu_path, :class => 'button' %>