config/routes.rb
Rails.application.routes.draw do

  root to: 'users#new'

  get 'users/new' => 'users#new', as: :new_user

  post 'users' => 'users#create'

  get '/login'     => 'sessions#new'

  post '/login'    => 'sessions#create'

  delete '/logout' => 'sessions#destroy'

  get '/realestate' => 'realestate#new', as: :new_realestate

  post '/realestate' =>'realestate#create'

  get '/house' => 'house#new'

  post '/house' => 'house#create'

  get '/house/show' => 'house#show'

  get '/house/:id/interested' => 'house#interest', as: :house_interested

  get '/realestate/show' => 'realestate#show'

  get '/user/:id/edit' => 'users#edit', as: :user_edit

  post '/user/:id/edit' => 'users#update'

  get '/house/:id/edit' => 'house#edit', as: :house_edit

  post '/house/:id/edit' => 'house#update'

  get '/user/menu' => 'users#menu'

  get '/user/show' => 'users#show'

  get '/realestate/:id/edit' => 'realestate#edit', as: :realestate_edit

  post '/realestate/:id/edit' => 'realestate#update'

  get 'inquiry/new' => 'inquiry#new', as: :new_inquiry

  post 'inquiry/new' => 'inquiry#create'

  get 'inquiry/show' => 'inquiry#show'

  get 'inquiry/:id/edit' => 'inquiry#edit'

  post 'inquiry/:id/edit' => 'inquiry#update', as: :inquiry_edit

  get 'inquiry/:id/reply' => 'inquiry#reply', as: :inquiry_reply

  post 'inquiry/:id/reply' => 'inquiry#reply_update'

  get '/users/:id/destroy' => 'users#destroy', as: :users_destroy

  get '/inquiry/:id/destroy' => 'inquiry#destroy', as: :inquiry_destroy

  get '/house/:id/destroy' => 'house#destroy', as: :house_destroy

  get '/realestate/:id/destroy' => 'realestate#destroy', as: :realestate_destroy
end

app/models/inquiry.rb
class Inquiry < ActiveRecord::Base
  validates :subject, :presence =>{:message => "Subject cannot be empty"}
  validates :message, :presence =>{:message => "Message cannot be empty"}
end

app/controllers/inquiry_controller.rb
class InquiryController < ApplicationController
  def new
    @inquiry = Inquiry.new
  end

  def create
    @inquiry = Inquiry.new(inquiry_params)
    @inquiry.househunterid = current_user.id

    if @inquiry.save
      # If user saves in the db successfully:
      flash[:notice] = "Inquiry created successfully!"
      redirect_to user_menu_path

    else
      # If user fails model validation - probably a bad password or duplicate email:
      flash.now.alert = "Couldn't create inquiry"
      flash.now.alert = @inquiry.errors.full_messages
      render :new
    end
  end

  def show
    @inquiry = Inquiry.all
  end

  def edit
    @inquiry = Inquiry.find_by_id(params[:id])
    if @inquiry == nil
      flash[:notice] = "Record not found!"
      render 'inquiry/show'
    end
  end

  def update
    @inquiry = Inquiry.find(params[:id])
    if @inquiry.update_attributes(inquiry_params)
      # Handle a successful update.
      flash[:notice] = "Updated successfully!"
      redirect_to user_menu_path
    else
      render 'edit'
    end
  end

  def reply_update
    @inquiry = Inquiry.find(params[:id])
    if @inquiry.update_attributes(inquiry_params)
      flash[:notice] = "Replied"
      render 'inquiry/show'
    end
  end

  def reply
    @inquiry = Inquiry.find_by_id(params[:id])
    if @inquiry == nil
      flash[:notice] = "Inquiry not found"
    end

  end

  def destroy
    @inquiry = Inquiry.find_by_id(params[:id])
    if @inquiry != nil
      Inquiry.find(params[:id]).destroy
      flash[:success] = "User deleted"
      redirect_to menu_path
    else
      flash[:notice] = "Record not found"
    end

  end


  private
  def inquiry_params
    # strong parameters - whitelist of allowed fields #=> permit(:name, :email, ...)
    # that can be submitted by a form to the user model #=> require(:user)
    params.permit(:househunterid, :subject, :message, :reply)
  end
end

app/helpers/inquiry_helper.rb
module InquiryHelper
end

app/views/inquiry/edit.html.erb
<% provide(:title, "Edit Inquiry") %>
<h1>Edit Inquiry Information</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for :inquiry do |f| %>

      <%= f.label :subject %>
      <%= f.text_field :subject, class: 'form-control' %>
      </br>
      <%= f.label :message %>
      <%= f.text_field :message, class: 'form-control' %>
      </br>
      <%= f.submit "Save changes", class: "btn btn-primary" %>

      <%= link_to 'Back', realestate_show_path%>
    <% end %>
  </div>
</div>

app/views/inquiry/new.html.erb
<h1>Inquiry Information</h1>

<%= form_for :inquiry do |f| %>

  <div>
    <%= f.label :subject %>
    <%= f.text_field :subject %>
  </div>
  <div>
    <%= f.label :message %>
    <%= f.text_area :message, autofocus: true %>
  </div>
  <div>
    <%= f.submit "Submit Inquiry" %>
  </div>

<% end %>

app/views/inquiry/reply.html.erb
<h1>Reply to Inquiry</h1>

  <%= form_for :inquiry do |f| %>
  <div>
    Subject :
    <%= @inquiry.subject %>
  </div>
  <div>
    Message :
    <%= @inquiry.message %>
  </div>
  <div>
    <%= f.label :reply %>
    <%= f.text_area :reply %>
  </div>
  <div>
    <%= f.submit "Submit Inquiry" %>
  </div>

<% end %>

app/views/inquiry/show.html.erb
<h2>Inquiry Details</h2>
<% @inquiry = Inquiry.all %>
<table id="inquiry" role="datatable">
  <thead>
  <tr>
    <th>Subject</th>
    <th>Message</th>
    <th>Edit</th>
    <th>Delete</th>
    <th>Reply</th>
  </tr>
  </thead>
  <tbody>
  <% @inquiry.each do |inquiry| %>
  <% if current_user.user_type == "Realestate Hunter" %>
    <% if current_user.id === inquiry.househunterid.to_i %>
      <tr>
        <td>
          <%= inquiry.subject %>
        </td>

        <td>
          <%= inquiry.message %>
        </td>
        <td>
          <%= inquiry.reply %>
        </td>
        <td>
          <%= link_to "Edit", inquiry_edit_path(inquiry.id) %>
        </td>
        <td>
          <%= link_to "Delete", inquiry_destroy_path(inquiry.id) %>
        </td>
      </tr>
    <% end %>
  <% elsif current_user.user_type == "Realtor" %>
      <tr>
        <td>
          <%= inquiry.id %>
        </td>

        <td>
          <%= inquiry.subject %>
        </td>

        <td>
          <%= inquiry.message %>
        </td>
        <td>

        </td>
        <td>

        </td>
        <td>
          <%= link_to "Reply", inquiry_reply_path(inquiry.id) %>
        </td>
      </tr>
      <% else %>
      <tr>
        <td>
          <%= inquiry.subject %>
        </td>

        <td>
          <%= inquiry.message %>
        </td>
        <td>
          <%= inquiry.reply %>
        </td>
        <td>
          <%= link_to "Edit", inquiry_edit_path(inquiry.id) %>
        </td>
        <td>
          <%= link_to "Delete", inquiry_destroy_path(inquiry.id) %>
        </td>
        <td>
          <%= link_to "Reply", inquiry_reply_path(inquiry.id) %>
        </td>
      </tr>
    <%end %>
  <%end %>
  </tbody>
</table>


<%= link_to 'Back', user_menu_path, :class => 'button' %>