config/routes.rb
Rails.application.routes.draw do

  root to: 'users#new'

  get 'users/new' => 'users#new', as: :new_user

  post 'users' => 'users#create'

  get '/login'     => 'sessions#new'

  post '/login'    => 'sessions#create'

  delete '/logout' => 'sessions#destroy'

  get '/realestate' => 'realestate#new', as: :new_realestate

  post '/realestate' =>'realestate#create'

  get '/house' => 'house#new'

  post '/house' => 'house#create'

  get '/house/show' => 'house#show'

  get '/house/:id/interested' => 'house#interest', as: :house_interested

  get '/realestate/show' => 'realestate#show'

  get '/user/:id/edit' => 'users#edit', as: :user_edit

  post '/user/:id/edit' => 'users#update'

  get '/house/:id/edit' => 'house#edit', as: :house_edit

  post '/house/:id/edit' => 'house#update'

  get '/user/menu' => 'users#menu'

  get '/user/show' => 'users#show'

  get '/realestate/:id/edit' => 'realestate#edit', as: :realestate_edit

  post '/realestate/:id/edit' => 'realestate#update'

  get 'inquiry/new' => 'inquiry#new', as: :new_inquiry

  post 'inquiry/new' => 'inquiry#create'

  get 'inquiry/show' => 'inquiry#show'

  get 'inquiry/:id/edit' => 'inquiry#edit'

  post 'inquiry/:id/edit' => 'inquiry#update', as: :inquiry_edit

  get 'inquiry/:id/reply' => 'inquiry#reply', as: :inquiry_reply

  post 'inquiry/:id/reply' => 'inquiry#reply_update'

  get '/users/:id/destroy' => 'users#destroy', as: :users_destroy

  get '/inquiry/:id/destroy' => 'inquiry#destroy', as: :inquiry_destroy

  get '/house/:id/destroy' => 'house#destroy', as: :house_destroy

  get '/realestate/:id/destroy' => 'realestate#destroy', as: :realestate_destroy
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>HouseRental</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<% if current_user %>
  <!-- current_user will return true if a user is logged in -->
  <%= "Logged in as #{current_user.email}" %> | <%= link_to 'Home', user_menu_path %> | <%= link_to 'Log Out', logout_path, method: :delete %> | <%= link_to "Edit Profile", user_edit_path(current_user) %>
<% else %>
  <!-- not logged in -->
  <%= link_to 'Home', root_path %> | <%= link_to 'Log In', login_path %> or <%= link_to 'Sign Up', new_user_path %>
<% end %>

<hr>

<% if notice %>
  <%= notice %>
<% end %>

<% if alert %>
  <%= alert %>
<% end %>



<%= yield %>

</body>
</html>